"use client";

import Image from "next/image";
import Link from "next/link";
import { useState } from "react";
import styles from "./discover.module.css";

const providers = [
  { id:"sonnenhof", category:"Location", name:"Gut Sonnenhof", city:"Köln · 34 km", image:"/demo-providers/location-sonnenhof.jpg", price:"ab 6.900 €", match:"97%", summary:"Historischer Gutshof für entspannte Feiern im Grünen.", facts:["40–140 Gäste","Freie Trauung im Garten","Exklusive Nutzung bis 02:00 Uhr"], offerings:["Innenhof & Dinnerbereich","Festscheune","Getting-ready-Suite"] },
  { id:"luma", category:"Fotografie", name:"Luma Fotografie", city:"Köln · 12 km", image:"/demo-providers/photography-luma.jpg", price:"ab 2.400 €", match:"96%", summary:"Natürliche Hochzeitsreportagen mit dokumentarischer und zeitloser Bildsprache.", facts:["8–12 Stunden Begleitung","Vorschau innerhalb von 72 Stunden","Online-Galerie in 4–6 Wochen"], offerings:["Standesamt · 4 Stunden · ab 1.290 €","Reportage · 8 Stunden · ab 2.400 €","Ganztagsreportage · 12 Stunden · ab 3.250 €"], profileHref:"/discover/luma?demo=1" },
  { id:"lumiere", category:"Catering", name:"Lumière Catering", city:"Düsseldorf · 18 km", image:"/demo-providers/catering-menu.jpg", price:"ab 89 € / Person", match:"94%", summary:"Saisonale Hochzeitsmenüs mit moderner, natürlicher Handschrift.", facts:["30–220 Gäste","Vegetarisch & vegan","Verkostung vor Buchung"], offerings:["Geröstete Marktgemüse · Kräutercreme","Geschmorte Rinderbacke · Sellerie · Jus","Zitronentarte · Holunder · Beeren"] },
] as const;

export default function DiscoverDemo() {
  const [selected,setSelected]=useState<(typeof providers)[number]|null>(null); const [gate,setGate]=useState(false); const [services,setServices]=useState<string[]>(["Location"]); const [city,setCity]=useState("Köln"); const [radius,setRadius]=useState(50); const [startDate,setStartDate]=useState("2027-06-19"); const [endDate,setEndDate]=useState("2027-06-19"); const [weekday,setWeekday]=useState("Samstag"); const [bundle,setBundle]=useState(false);
  const results=providers.filter(provider=>services.includes(provider.category)&&provider.city.split(" ·")[0].toLowerCase().includes(city.toLowerCase().trim())&&Number(provider.city.match(/(\d+) km/)?.[1]||0)<=radius);
  return <main className={styles.shell}>
    <header><Link href="/">Ouivio<span>.</span></Link><div><small>Hochzeit planen</small><strong>Anbieter entdecken</strong></div><button className={styles.partnerLink} onClick={()=>setGate(true)}>Warenkorb</button><Link className={styles.partnerLink} href="/login">Anmelden</Link></header>
    <section className={styles.hero}><small>Ouivio Auswahl</small><h1>Anbieter, die zu<br/>eurer Hochzeit passen.</h1><p>Vergleicht Stil, Leistungen, Kapazität und Preis – auf Basis derselben Daten, die Anbieter in ihrem Partnerbereich pflegen.</p></section>
    <section className={styles.searchPanel}><label>Frühester Termin<input type="date" value={startDate} onChange={e=>{setStartDate(e.target.value);if(e.target.value>endDate)setEndDate(e.target.value)}}/></label><label>Spätester Termin<input type="date" min={startDate} value={endDate} onChange={e=>setEndDate(e.target.value)}/></label><label>Wochentag<select value={weekday} onChange={e=>setWeekday(e.target.value)}><option>Freitag</option><option>Samstag</option><option>Sonntag</option><option>Flexibel</option></select></label><label>Ort<input value={city} onChange={e=>setCity(e.target.value)}/></label><label>Umkreis<select value={radius} onChange={e=>setRadius(Number(e.target.value))}><option value="25">25 km</option><option value="50">50 km</option><option value="100">100 km</option></select></label><div className={styles.serviceChoice}><strong>Leistungen</strong><div>{["Location","Catering","Fotografie"].map(service=><button key={service} aria-pressed={services.includes(service)} onClick={()=>{setBundle(false);setServices(current=>current.includes(service)?current.filter(item=>item!==service):[...current,service])}}>{service}</button>)}<button aria-pressed={bundle} onClick={()=>{setBundle(true);setServices(["Location","Catering","Fotografie"])}}>Komplettpaket</button></div></div><p>{results.length} passende Anbieter · {startDate.split("-").reverse().join(".")}–{endDate.split("-").reverse().join(".")} · {weekday}{bundle?" · Bundle bevorzugt":" · einzeln kombinierbar"}</p></section>
    <section className={styles.grid}>{results.map(provider=><article key={provider.id}><button className={styles.card} onClick={()=>setSelected(provider)}><div className={styles.image}><Image alt={`${provider.name} – ${provider.category}`} fill sizes="(max-width: 760px) 100vw, 50vw" src={provider.image}/><b>{provider.match} Match</b></div><div className={styles.cardBody}><small>{provider.category} · {provider.city}</small><h2>{provider.name}</h2><p>{provider.summary}</p><div><strong>{provider.price}</strong><span>Profil ansehen →</span></div></div></button></article>)}</section>{!results.length&&<p className={styles.empty}>Keine passende Entwicklungsoption gefunden. Ort oder Umkreis anpassen.</p>}
    {selected&&<section className={styles.detail} aria-label={`${selected.name} Profil`}><button className={styles.close} onClick={()=>setSelected(null)}>Schließen ×</button><div className={styles.detailImage}><Image alt={`${selected.name} Titelbild`} fill sizes="50vw" src={selected.image}/></div><div className={styles.detailBody}><small>{selected.category} · {selected.match} Match</small><h2>{selected.name}</h2><p>{selected.summary}</p><h3>Leistungen</h3><ul>{selected.offerings.map(item=><li key={item}>{item}</li>)}</ul><button className={styles.request} onClick={()=>setGate(true)}>Merken oder Verfügbarkeit prüfen</button><em>Ohne Konto vergleichen · Konto erst für persönliche Aktionen</em></div></section>}{gate&&<section className={styles.accountGate} role="dialog"><button onClick={()=>setGate(false)}>×</button><h2>Für Merkliste und Warenkorb braucht ihr ein Konto.</h2><p>So bleibt eure Planung auf allen Geräten erhalten.</p><Link href="/login">Anmelden oder Konto anlegen</Link></section>}
  </main>;
}
