"use client";

import Image from "next/image";
import Link from "next/link";
import { useRouter } from "next/navigation";
import { useEffect, useState } from "react";
import { getSupabaseClient } from "../../lib/supabase";
import { bookingStartForDate } from "../../lib/booking-availability";
import { fetchFavoritePackageIds, toggleFavoritePackage } from "../../lib/favorite-packages";
import { saveCartPackage } from "../../lib/cart-items";
import { ensureAccountProfile } from "../../lib/account";
import { ensureWeddingWorkspace } from "../../lib/workspace";
import styles from "./discover.module.css";

type Provider = { id: string; packageId?: string; category: string; name: string; city: string; image: string; price: string; match: string; summary: string; facts: string[]; offerings: string[]; profileHref?: string };
type SearchCriteria = { services: string[]; city: string; radius: number; startDate: string; endDate: string; weekday: string; bundle: boolean };

const providers: Provider[] = [
  { id:"sonnenhof", category:"Location", name:"Gut Sonnenhof", city:"Köln · 34 km", image:"/demo-providers/location-sonnenhof.jpg", price:"ab 6.900 €", match:"97%", summary:"Historischer Gutshof für entspannte Feiern im Grünen.", facts:["40–140 Gäste","Freie Trauung im Garten","Exklusive Nutzung bis 02:00 Uhr"], offerings:["Innenhof & Dinnerbereich","Festscheune","Getting-ready-Suite"] },
  { id:"luma", category:"Fotografie", name:"Luma Fotografie", city:"Köln · 12 km", image:"/demo-providers/photography-luma.jpg", price:"ab 2.400 €", match:"96%", summary:"Natürliche Hochzeitsreportagen mit dokumentarischer und zeitloser Bildsprache.", facts:["8–12 Stunden Begleitung","Vorschau innerhalb von 72 Stunden","Online-Galerie in 4–6 Wochen"], offerings:["Standesamt · 4 Stunden · ab 1.290 €","Reportage · 8 Stunden · ab 2.400 €","Ganztagsreportage · 12 Stunden · ab 3.250 €"], profileHref:"/discover/luma?demo=1" },
  { id:"lumiere", category:"Catering", name:"Lumière Catering", city:"Düsseldorf · 18 km", image:"/demo-providers/catering-menu.jpg", price:"ab 89 € / Person", match:"94%", summary:"Saisonale Hochzeitsmenüs mit moderner, natürlicher Handschrift.", facts:["30–220 Gäste","Vegetarisch & vegan","Verkostung vor Buchung"], offerings:["Geröstete Marktgemüse · Kräutercreme","Geschmorte Rinderbacke · Sellerie · Jus","Zitronentarte · Holunder · Beeren"] },
] as const;

const cityOptions = ["Alle Städte", "Köln", "Düsseldorf", "Bonn"] as const;

export default function DiscoverDemo() {
  const router=useRouter(); const [selected,setSelected]=useState<Provider|null>(null); const [gate,setGate]=useState(false); const [isAuthenticated,setIsAuthenticated]=useState(false); const [accountHref,setAccountHref]=useState("/dashboard"); const [accountLabel,setAccountLabel]=useState("Mein Dashboard"); const [services,setServices]=useState<string[]>(["Location"]); const [city,setCity]=useState("Köln"); const [radius,setRadius]=useState(50); const [startDate,setStartDate]=useState("2027-06-19"); const [endDate,setEndDate]=useState("2027-06-19"); const [weekday,setWeekday]=useState("Samstag"); const [bundle,setBundle]=useState(false); const [criteria,setCriteria]=useState<SearchCriteria>({services:["Location"],city:"Köln",radius:50,startDate:"2027-06-19",endDate:"2027-06-19",weekday:"Samstag",bundle:false}); const [selection,setSelection]=useState<Provider[]>([]); const [selectionOpen,setSelectionOpen]=useState(false); const [checkoutBusy,setCheckoutBusy]=useState(false); const [liveProviders,setLiveProviders]=useState<Provider[]>([]); const [favoritePackageIds,setFavoritePackageIds]=useState<Set<string>>(new Set()); const [favoriteWeddingId,setFavoriteWeddingId]=useState(""); const [favoriteBusy,setFavoriteBusy]=useState(false); const [favoriteMessage,setFavoriteMessage]=useState("");
  useEffect(()=>{const params=new URLSearchParams(window.location.search);const nextStart=params.get("start")||startDate;const nextEnd=params.get("end")||nextStart;const nextCity=params.get("city")||city;setStartDate(nextStart);setEndDate(nextEnd);setCity(nextCity);setCriteria(current=>({...current,startDate:nextStart,endDate:nextEnd,city:nextCity}));},[]);
  useEffect(()=>{let active=true;void (async()=>{const {data}=await getSupabaseClient().auth.getUser();if(!data.user)return;const account=await ensureAccountProfile(data.user);if(account.type==="partner"){if(active){setIsAuthenticated(true);setAccountHref("/partner");setAccountLabel("Partner-Dashboard");}return;}const weddingId=await ensureWeddingWorkspace(data.user);if(!active)return;setIsAuthenticated(true);setAccountHref("/dashboard");setAccountLabel("Mein Dashboard");setFavoriteWeddingId(weddingId);try{const ids=await fetchFavoritePackageIds(weddingId);if(active)setFavoritePackageIds(ids);}catch{if(active)setFavoriteMessage("Eure Merkliste wird gerade aktualisiert.");}})().catch(()=>{});return()=>{active=false};},[]);
  useEffect(()=>{let active=true;const load=async()=>{const {data,error}=await getSupabaseClient().rpc("search_published_partner_packages",{requested_service_types:criteria.services.map(service=>service.toLowerCase()==="fotografie"?"photography":service.toLowerCase()),requested_city:criteria.city.trim()||null,requested_starts_at:bookingStartForDate(criteria.startDate)});if(error||!active)return;const imageFor=(type:string)=>type==="location"?"/demo-providers/location-sonnenhof.jpg":type==="catering"?"/demo-providers/catering-menu.jpg":"/demo-providers/photography-luma.jpg";setLiveProviders((data??[]).map((item:{package_id:string;service_type:string;partner_name:string;city:string|null;package_name:string;description:string|null;price_amount:number;currency:string;duration_minutes:number;included_items:string[];booking_mode:string})=>({id:item.package_id,packageId:item.package_id,category:item.service_type==="photography"?"Fotografie":item.service_type.charAt(0).toUpperCase()+item.service_type.slice(1),name:item.partner_name,city:item.city||"Ort folgt",image:imageFor(item.service_type),price:`ab ${new Intl.NumberFormat("de-DE",{style:"currency",currency:item.currency}).format(Number(item.price_amount))}`,match:"Live",summary:item.description||`${item.package_name} · veröffentlichtes Anbieterpaket`,facts:[`${item.duration_minutes/60} Stunden`,`Zum gewählten Termin verfügbar`,item.booking_mode==="standalone"?"Einzeln kombinierbar":"Anbieterregel beachten"],offerings:[item.package_name,...(item.included_items||[])]})));};void load();return()=>{active=false};},[criteria]);
  const visibleProviders=liveProviders.length?liveProviders:providers;
  const results=visibleProviders.filter(provider=>{const providerCity=provider.city.split(" ·")[0].trim().toLocaleLowerCase("de-DE");const requestedCity=criteria.city.trim().toLocaleLowerCase("de-DE");const cityMatches=!requestedCity||providerCity===requestedCity;const distance=Number(provider.city.match(/(\d+) km/)?.[1]||0);return criteria.services.includes(provider.category)&&cityMatches&&(liveProviders.length||distance<=criteria.radius)});
  const updateServiceSelection=(service:string)=>{const next=services.includes(service)?services.filter(item=>item!==service):[...services,service];setServices(next);setBundle(false);setCriteria(current=>({...current,services:next,bundle:false}));};
  const selectBundle=()=>{const next=["Location","Catering","Fotografie"];setServices(next);setBundle(true);setCriteria(current=>({...current,services:next,bundle:true}));};
  const addToSelection=async()=>{if(!selected)return;if(!isAuthenticated){setGate(true);return;}if(!selected.packageId){setFavoriteMessage("Diese statische Demo-Karte kann nicht in euren Warenkorb. Wählt ein Live-Angebot aus der Suche.");return;}setFavoriteBusy(true);setFavoriteMessage("");try{const {data}=await getSupabaseClient().auth.getUser();if(!data.user){setGate(true);return;}const weddingId=favoriteWeddingId||await ensureWeddingWorkspace(data.user);if(!favoriteWeddingId)setFavoriteWeddingId(weddingId);await saveCartPackage(weddingId,selected.packageId,startDate,endDate);setSelection(current=>current.some(provider=>provider.id===selected.id)?current:[...current,selected]);setSelectionOpen(true);setFavoriteMessage("In eure Auswahl gespeichert. Ihr findet das Angebot auch im Dashboard unter Warenkorb.");}catch{setFavoriteMessage("Der Warenkorb konnte gerade nicht gespeichert werden.");}finally{setFavoriteBusy(false);}};
  const removeFromSelection=(id:string)=>setSelection(current=>current.filter(provider=>provider.id!==id));
  const continueToCheckout=async()=>{if(!selection.length)return;setCheckoutBusy(true);try{const {data}=await getSupabaseClient().auth.getUser();if(!data.user){setGate(true);return;}const query=new URLSearchParams({start:startDate,end:endDate});const packageIds=selection.map(provider=>provider.packageId).filter((id):id is string=>Boolean(id));if(packageIds.length===selection.length)query.set("packages",packageIds.join(","));else query.set("items",selection.map(provider=>provider.id).join(","));router.push(`/discover/cart?${query.toString()}`);}finally{setCheckoutBusy(false);}};
  const toggleSelectedFavorite=async()=>{if(!selected)return;const {data}=await getSupabaseClient().auth.getUser();if(!data.user){setGate(true);return;}if(!selected.packageId){setFavoriteMessage("Diese statische Demo-Karte kann nicht gespeichert werden. Wählt ein Live-Angebot aus der Suche.");return;}setFavoriteBusy(true);setFavoriteMessage("");try{const weddingId=favoriteWeddingId||await ensureWeddingWorkspace(data.user);if(!favoriteWeddingId)setFavoriteWeddingId(weddingId);const saved=await toggleFavoritePackage(weddingId,selected.packageId,favoritePackageIds.has(selected.packageId));setFavoritePackageIds(current=>{const next=new Set(current);if(saved)next.add(selected.packageId!);else next.delete(selected.packageId!);return next;});setFavoriteMessage(saved?"In eurer Merkliste gespeichert.":"Aus eurer Merkliste entfernt.");}catch{setFavoriteMessage("Die Merkliste konnte gerade nicht aktualisiert werden.");}finally{setFavoriteBusy(false);}};
  return <main className={styles.shell}>
    <header><Link href="/index.html#top">Ouivio<span>.</span></Link><div><small>Hochzeit planen</small><strong>Anbieter entdecken</strong></div><Link className={styles.partnerLink} href="/login?intent=partner">Für Anbieter</Link>{isAuthenticated?<Link className={styles.accountLink} href={accountHref}><span aria-hidden="true">●</span>{accountLabel} →</Link>:<Link className={styles.partnerLink} href="/login">Anmelden</Link>}</header>
    <section className={styles.hero}>
      <small>Ouivio Auswahl</small>
      <h1>Plant eure Hochzeit<br/>an einem schönen Ort.</h1>
      <p>Entdeckt freie Locations und passende Hochzeitsprofis – nach Termin, Ort und euren Wünschen.</p>
      {liveProviders.length>0&&<p className={styles.liveNote}>Live-Angebote · Belegte Pakete bleiben für euren Termin unsichtbar.</p>}
    </section>
    <section className={styles.searchPanel} aria-label="Anbieter suchen">
      <div className={styles.searchBar}>
        <label><span className={styles.fieldIcon} aria-hidden="true">◷</span><span><b>Wann?</b><small>Frühester Termin</small></span><input aria-label="Frühester Termin" type="date" value={startDate} onChange={e=>{const next=e.target.value;const nextEnd=next>endDate?next:endDate;setStartDate(next);setEndDate(nextEnd);setCriteria(current=>({...current,startDate:next,endDate:nextEnd}))}}/></label>
        <label><span className={styles.fieldIcon} aria-hidden="true">↔</span><span><b>Zeitraum</b><small>Spätester Termin</small></span><input aria-label="Spätester Termin" type="date" min={startDate} value={endDate} onChange={e=>{const next=e.target.value;setEndDate(next);setCriteria(current=>({...current,endDate:next}))}}/></label>
        <label><span className={styles.fieldIcon} aria-hidden="true">⌖</span><span><b>Wo?</b><small>Ort &amp; Umkreis</small></span><select aria-label="Ort" value={city || "Alle Städte"} onChange={e=>{const next=e.target.value === "Alle Städte" ? "" : e.target.value;setCity(next);setCriteria(current=>({...current,city:next}))}}>{cityOptions.map(option=><option key={option}>{option}</option>)}</select></label>
        <label><span className={styles.fieldIcon} aria-hidden="true">☼</span><span><b>Welcher Tag?</b><small>Wochentag</small></span><select aria-label="Wochentag" value={weekday} onChange={e=>{const next=e.target.value;setWeekday(next);setCriteria(current=>({...current,weekday:next}))}}><option>Freitag</option><option>Samstag</option><option>Sonntag</option><option>Flexibel</option></select></label>
      </div>
      <div className={styles.searchOptions}>
        <div className={styles.radiusChoice}><span>Umkreis</span><select aria-label="Umkreis" value={radius} onChange={e=>{const next=Number(e.target.value);setRadius(next);setCriteria(current=>({...current,radius:next}))}}><option value="25">25 km</option><option value="50">50 km</option><option value="100">100 km</option></select></div>
        <div className={styles.serviceChoice}><strong>Was braucht ihr?</strong><div>{["Location","Catering","Fotografie"].map(service=><button key={service} type="button" aria-pressed={services.includes(service)} onClick={()=>updateServiceSelection(service)}>{service}</button>)}<button type="button" aria-pressed={bundle} onClick={selectBundle}>Alles als Paket</button></div></div>
      </div>
      <p className={styles.searchSummary}><b>{results.length}</b> passende Anbieter · {criteria.startDate.split("-").reverse().join(".")}–{criteria.endDate.split("-").reverse().join(".")} · {criteria.weekday}{criteria.bundle?" · Komplettpaket":" · frei kombinierbar"}</p>
    </section>
    <section className={styles.resultsHead} id="suchergebnisse"><div><small>Für eure Auswahl</small><h2>Passende Anbieter</h2></div><p>Vergleicht Verfügbarkeit, Stil und Preis in Ruhe.</p></section>
    <section className={styles.grid}>{results.map(provider=><article key={provider.id}><button className={styles.card} onClick={()=>setSelected(provider)}><div className={styles.image}><Image alt={`${provider.name} – ${provider.category}`} fill sizes="(max-width: 760px) 100vw, 50vw" src={provider.image}/><b>{provider.match} Match</b></div><div className={styles.cardBody}><small>{provider.category} · {provider.city}</small><h2>{provider.name}</h2><p>{provider.summary}</p><div><strong>{isAuthenticated?provider.price:"Preis nach Anmeldung"}</strong><span>Verfügbarkeit ansehen →</span></div></div></button></article>)}</section>{!results.length&&<p className={styles.empty}>Keine passende Entwicklungsoption gefunden. Ort oder Umkreis anpassen.</p>}
    {selected&&<section className={styles.detail} aria-label={`${selected.name} Profil`}><button className={styles.close} onClick={()=>setSelected(null)}>Schließen ×</button><div className={styles.detailImage}><Image alt={`${selected.name} Titelbild`} fill sizes="50vw" src={selected.image}/></div><div className={styles.detailBody}><small>{selected.category} · {selected.match} Match</small><h2>{selected.name}</h2><p>{selected.summary}</p>{isAuthenticated?<><h3>Leistungen</h3><ul>{selected.offerings.map(item=><li key={item}>{item}</li>)}</ul><div className={styles.detailActions}><button aria-pressed={Boolean(selected.packageId&&favoritePackageIds.has(selected.packageId))} className={styles.save} disabled={favoriteBusy} onClick={()=>void toggleSelectedFavorite()}>{selected.packageId&&favoritePackageIds.has(selected.packageId)?"♥ Gemerkt":"♡ Merken"}</button><button className={styles.request} disabled={favoriteBusy} onClick={()=>void addToSelection()}>{selection.some(provider=>provider.id===selected.id)?"Im Warenkorb":"In den Warenkorb"}</button></div>{favoriteMessage&&<p className={styles.liveNote} role="status">{favoriteMessage}</p>}</>:<div className={styles.detailActions}><button className={styles.request} onClick={()=>setGate(true)}>Preise & Details freischalten →</button></div>}<em>{isAuthenticated?"Merkliste und Warenkorb sind getrennt und werden beide in eurem Konto gespeichert.":"Verfügbarkeit ist offen sichtbar. Preise, Details, Merkliste und Warenkorb werden nach Anmeldung freigeschaltet."}</em></div></section>}
    {selectionOpen&&<aside className={styles.selectionTray} aria-label="Eure Auswahl"><button className={styles.trayClose} aria-label="Auswahl schließen" onClick={()=>setSelectionOpen(false)}>×</button><small>Eure Hochzeitsauswahl</small><h2>{selection.length?`${selection.length} Leistung${selection.length===1?"":"en"} vorgemerkt`:"Noch nichts ausgewählt"}</h2><p>{selection.length?"Stellt eure Hochzeit zunächst frei zusammen. Beim Checkout wird eure Anmeldung geprüft; Zahlung und Reservierung erfolgen erst im nächsten Schritt.":"Wählt Location, Catering oder Fotografie aus und fügt passende Anbieter hinzu."}</p>{selection.length>0&&<ul>{selection.map(provider=><li key={provider.id}><span><strong>{provider.name}</strong><small>{provider.category} · {provider.price}</small></span><button aria-label={`${provider.name} entfernen`} onClick={()=>removeFromSelection(provider.id)}>Entfernen</button></li>)}</ul>}<button className={styles.checkout} disabled={!selection.length||checkoutBusy} onClick={continueToCheckout}>{checkoutBusy?"Konto wird geprüft …":"Zum Checkout"}</button></aside>}
    {gate&&<section className={styles.accountGate} role="dialog" aria-modal="true"><button onClick={()=>setGate(false)} aria-label="Dialog schließen">×</button><small>Eure Planung speichern</small><h2>Preise, Details und Warenkorb gibt es mit eurem Kundenkonto.</h2><p>Die Verfügbarkeit bleibt offen sichtbar. Mit einem Konto könnt ihr Angebote vergleichen, merken und eure Auswahl speichern.</p><Link href="/login?intent=customer">Kundenkonto erstellen</Link><Link href="/login">Bereits registriert? Anmelden</Link></section>}
  </main>;
}
